apiVersion: v1
kind: Service
metadata:
        name: express-server-service
spec:
        selector:
                app: express-server
        type: LoadBalancer
        ports:
        - protocol: TCP
          port: 5000
          targetPort: 3001
          nodePort: 31110
